repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: ["--remove"]

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf
