repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: ["--remove"]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: debug-statements

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
    -   id: python-check-blanket-noqa

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
    -   id: python-check-mock-methods

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
    -   id: python-no-eval

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
    -   id: python-no-log-warn

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
    -   id: rst-backticks

-   repo: https://github.com/openstack/bashate
    rev: 2.0.0
    hooks:
    -   id: bashate

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
    -   id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

-   repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]

-   repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args: [--safe, --quiet]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        additional_dependencies: [
          flake8-blind-except,
          flake8-bugbear,
          flake8-comprehensions,
          flake8-debugger,
          flake8-docstrings,
          flake8-isort,
          flake8-polyfill,
          flake8-pytest,
          flake8-quotes,
          flake8-typing-imports,
          yesqa]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
